//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Dic_WarehouseState
    {
        public T_Dic_WarehouseState()
        {
            this.T_Infor_Warehouse = new HashSet<T_Infor_Warehouse>();
        }
    
        public int Nid { get; set; }
        public int Code { get; set; }
        public string Decription { get; set; }
    
        public virtual ICollection<T_Infor_Warehouse> T_Infor_Warehouse { get; set; }
    }
}
