//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Infor_Indent
    {
        public int Iid { get; set; }
        public Nullable<long> ICode { get; set; }
        public string IContent { get; set; }
        public Nullable<System.DateTime> ISigningDate { get; set; }
        public Nullable<System.DateTime> IExpirationDate { get; set; }
        public Nullable<int> IState { get; set; }
        public Nullable<System.DateTime> IDeliveryDate { get; set; }
        public string IRemarks { get; set; }
    
        public virtual T_Dic_IndentState T_Dic_IndentState { get; set; }
    }
}
