//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Infor_Staff
    {
        public int Sid { get; set; }
        public string SName { get; set; }
        public string SGender { get; set; }
        public Nullable<int> SAge { get; set; }
        public string SIdnumber { get; set; }
        public string SPhoneNumber { get; set; }
        public string SAddress { get; set; }
        public Nullable<System.DateTime> STakeOfficeDate { get; set; }
        public Nullable<int> SState { get; set; }
        public Nullable<System.DateTime> SHolidayEndDate { get; set; }
        public Nullable<int> SLevel { get; set; }
        public Nullable<int> SUserId { get; set; }
    
        public virtual T_Dic_Staff T_Dic_Staff { get; set; }
    }
}
