//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Infor_Truck
    {
        public int Tid { get; set; }
        public string TType { get; set; }
        public string TBrand { get; set; }
        public string TModel { get; set; }
        public string TLicensePlateNumber { get; set; }
        public Nullable<int> TGpSChipId { get; set; }
        public string TLocation { get; set; }
        public string TTerritory { get; set; }
        public Nullable<int> TDriverId { get; set; }
        public Nullable<int> TState { get; set; }
        public string TTaskId { get; set; }
        public string TRemarks { get; set; }
    
        public virtual T_Dic_TruckState T_Dic_TruckState { get; set; }
    }
}
