//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportScheduling.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSEntities : DbContext
    {
        public TSEntities()
            : base("name=TSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<T_Dic_GoodsState> T_Dic_GoodsState { get; set; }
        public DbSet<T_Dic_IndentState> T_Dic_IndentState { get; set; }
        public DbSet<T_Dic_StaffState> T_Dic_StaffState { get; set; }
        public DbSet<T_Dic_TruckState> T_Dic_TruckState { get; set; }
        public DbSet<T_Dic_WarehouseState> T_Dic_WarehouseState { get; set; }
        public DbSet<T_Infor_Goods> T_Infor_Goods { get; set; }
        public DbSet<T_Infor_Indent> T_Infor_Indent { get; set; }
        public DbSet<T_Infor_Staff> T_Infor_Staff { get; set; }
        public DbSet<T_Infor_Truck> T_Infor_Truck { get; set; }
        public DbSet<T_Infor_UserLogin> T_Infor_UserLogin { get; set; }
        public DbSet<T_Infor_Warehouse> T_Infor_Warehouse { get; set; }
    }
}
